export const INIT_TODO = 'INIT_TODO'
export const ADD_TODO = 'ADD_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const UPDATEDANE_TODO = 'UPDATEDANE_TODO'
export const CREATE_MYPHOTO = 'CREATE_MYPHOTO'
